name: Build,Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  DOTNET_NOLOGO: true

jobs:
  dotnet-build-test-docker-build-push:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-18.04 ]
        version: [1.24.0.1, 1.25.0, 1.26.0]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore -p:TonClientVersion=${{ matrix.version }}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Run
        run: dotnet run --configuration Release --no-build --project ./EverscaleExample